version: '3.9'

services:
  db:
    image: 'postgres:latest'
    ports:
      - "5430:5432"
    environment:
      - POSTGRES_USER=korpatiy
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=musicdb
    networks:
      - music-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - music-net

networks:
  music-net:
    name: music-net