version: '3.9'

services:
  db:
    image: 'postgres:latest'
    container_name: musicdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=korpatiy
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=musicdb
