spring:
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
  datasource:
    driver-class-name: org.postgresql.Driver
    username: korpatiy
    password: postgres
    url: jdbc:postgresql://localhost:5430/musicdb